version: 0.2

phases:
  install:
    commands:
      - cd hello-world-js && npm install && cd ..
      - cd hello-world-java && gradle build && cd ..
      - aws cloudformation package --template-file template.yaml --s3-bucket sl-phil-test --output-template-file packaged.yaml
  build:
    commands:
      - cd hello-world-js && npm test && cd ..
artifacts:
  type: zip
  files:
    - template.yaml
    - packaged.yaml