version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test
      - npm run build
artifacts:
  files:
    - hello.zip
  name: hello-$(date +%Y-%m-%d).zip