version: 0.2

phases:
  install:
    commands:
      - cd hello-world-java && chmod +x gradlew && ./gradlew build && cd ..
      - aws cloudformation package --template-file template.yaml --s3-bucket sl-phil-test --output-template-file packaged.yaml
  build:
    commands:
      - cd hello-world-js && npm test && cd ..
artifacts:
  secondary-artifacts:
    template:
      type: zip
      files:
        - template.yaml
        - packaged.yaml
