version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test
artifacts:
  files:
    - hello.js
    - stack.cform
  name: hello-$(git rev-parse --short HEAD).zip