---
pipeline:
  name: Hello
  roleArn: arn:aws:iam::826925315321:role/service-role/AWSCodePipelineServiceRole-eu-west-2-Hello
  artifactStore:
    type: S3
    location: codepipeline-eu-west-2-463210198351
  stages:
    - name: Source
      actions:
        - name: Source
          actionTypeId:
            category: Source
            owner: ThirdParty
            provider: GitHub
            version: '1'
          runOrder: 1
          configuration:
            Branch: master
            OAuthToken: '****'
            Owner: ppinkowski
            PollForSourceChanges: 'false'
            Repo: aws-test
          outputArtifacts:
            - name: SourceArtifact
          inputArtifacts: []
          region: eu-west-2
    - name: Build
      actions:
        - name: Build
          actionTypeId:
            category: Build
            owner: AWS
            provider: CodeBuild
            version: '1'
          runOrder: 1
          configuration:
            ProjectName: Hello
          outputArtifacts:
            - name: LambdaArtifact
          inputArtifacts:
            - name: SourceArtifact
          region: eu-west-2
        - name: BuildClient
          actionTypeId:
            category: Build
            owner: AWS
            provider: CodeBuild
            version: '1'
          runOrder: 1
          configuration:
            ProjectName: HelloClient
          outputArtifacts:
            - name: ClientArtifact
          inputArtifacts:
            - name: SourceArtifact
          region: eu-west-2
    - name: Deploy
      actions:
        - name: Deploy
          actionTypeId:
            category: Deploy
            owner: AWS
            provider: CloudFormation
            version: '1'
          runOrder: 1
          configuration:
            ActionMode: CHANGE_SET_REPLACE
            Capabilities: CAPABILITY_IAM
            ChangeSetName: hello
            RoleArn: arn:aws:iam::826925315321:role/CFDeploy
            StackName: hello
            TemplatePath: LambdaArtifact::packaged.yaml
          outputArtifacts: []
          inputArtifacts:
            - name: LambdaArtifact
          region: eu-west-2
        - name: Execute
          actionTypeId:
            category: Deploy
            owner: AWS
            provider: CloudFormation
            version: '1'
          runOrder: 2
          configuration:
            ActionMode: CHANGE_SET_EXECUTE
            ChangeSetName: hello
            StackName: hello
          outputArtifacts: []
          inputArtifacts:
            - name: LambdaArtifact
          region: eu-west-2
        - name: DeploySite
          actionTypeId:
            category: Deploy
            owner: AWS
            provider: S3
            version: '1'
          runOrder: 3
          configuration:
            BucketName: sl-phil-aws-test-static-site
            Extract: 'true'
          outputArtifacts: []
          inputArtifacts:
            - name: ClientArtifact
          region: eu-west-2
  version: 10
metadata:
  pipelineArn: arn:aws:codepipeline:eu-west-2:826925315321:Hello
  created: 1551695990.419
  updated: 1551875986.758
