AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app
    Sample SAM Template for sam-app

Resources:
    HelloWorldJavaFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: hello-world-java/build/distributions/hello-java-1.0-SNAPSHOT.zip
            Handler: hello.HelloHandler::handleRequest
            Runtime: java8
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /hellojava
                        Method: get
    ClientBucket:
        Type: AWS::S3::Bucket
        Properties:
            AccessControl: PublicRead
            BucketName: sl-phil-aws-test-static-site
            WebsiteConfiguration:
                IndexDocument: index.html

Outputs:
    HelloWorldApi:
        Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hellojs/'

    HelloWorldJavaApi:
        Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hellojava/'

    HelloWorldFunction:
        Description: 'Hello World Lambda Function ARN'
        Value: !GetAtt HelloWorldFunction.Arn

    HelloWorldFunctionIamRole:
        Description: 'Implicit IAM Role created for Hello World function'
        Value: !GetAtt HelloWorldFunctionRole.Arn

    BucketName:
        Description: 'Client Bucket Name'
        Value: !Ref ClientBucket
