version: 0.2

phases:
  install:
    commands:
      - npm i -g yarn
      - yarn install
  build:
    commands:
      - yarn build
artifacts:
  type: zip
  base-directory: build
  files:
    - '**/*'
