version: 0.2

phases:
  install:
    commands:
      - npm i -g yarn
      - cd op-portal && yarn install
  build:
    commands:
      - yarn build
artifacts:
  type: zip
  base-directory: op-portal/build
  files:
    - '**/*'
